version: '3.4'

services:
    dotnet5metricslogsgrafana:
        image: ${DOCKER_REGISTRY-}dotnet5metricslogsgrafana
        container_name: dotnet5api
        build:
            context: .
            dockerfile: Dotnet5MetricsLogsGrafana/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development     
        networks:
            - loki

    loki:
        image: grafana/loki:1.6.0
        container_name: loki
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - loki

    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
        volumes:
            - grafana:/var/lib/grafana
        networks:
            - loki

    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8090:8090"
        environment:
            - INFLUXDB_DB=appmetricsdemo
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
        volumes:
            - influxdb:/var/lib/influxdb
        networks:
            - loki
networks:
    loki:
        name: dotnet5metricslogsgrafana
volumes:
    influxdb:
    grafana:
