{
 "title": "Simple AppMetrics .NET5",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Http Exceptions Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__exceptions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregated error count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "application.httprequests__errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors per endpoint (rate 1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route",
     "groupBy": [
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "application.httprequests__error_rate_per_endpoint_and_status_code",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Endpoint rate",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 5, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route",
     "groupBy": [
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Error Code (count/interval)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "HTTP $tag_http_status_code",
     "groupBy": [
      { "params": [ "http_status_code" ], "type": "tag" }
     ],
     "measurement": "application.httprequests__error_rate_per_endpoint_and_status_code",
     "select": [
      [
       { "params": [ "count.meter" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}